### ISSUE TITLE
CMS Page

### ISSUE THREAD

**Issue by rayt86** [PyCon/pycon#506]
Nav
* [x] Just above 980px the logo is needs to be centered in between the edge of the screen and the navigation. It is currently to close to the nav.
* [x] The “you are here” underline in the mockup nav bar (a) is tightly attached beneath its word, (b) does not stick out from under its word in either direction, and (c) is several pixels high to give it weight and to visually match the stroke width of the nice and weighty font. The line is too far beneath the word, and sticks out awkwardly to the right. It should be made to match the mockup if possible.

Breadcrumbs
* [x] The green breadcrumb container needs to be shorter and match the mockup i.e. less space above and below the breadcrumb text.
* [x] Use Roboto Condensed Bold for the breadcrumb font.

**Comment by rayt86** [comment]
PR in for this issue

**Comment by dpoirier** [comment]
Fixed #519

**Comment by hatlas** [comment]
> The “you are here” underline in the mockup nav bar (a) is tightly attached beneath its word, (b) does not stick out from under its word in either direction, and (c) is several pixels high to give it weight and to visually match the stroke width of the nice and weighty font. The line is too far beneath the word, and sticks out awkwardly to the right. It should be made to match the mockup if possible.

Possibly not fixed.
![screen shot 2015-09-03 at 3 02 03 pm](https://cloud.githubusercontent.com/assets/8808771/9667951/cddf5054-524c-11e5-974f-60fd99270376.png)
It sticks out a little to the right, which looks different from the mockup.
https://asset1.basecamp.com/1849796/projects/9507827/attachments/168120421/4d5c233e07977fcbb483937e568998fd0010/original/CMS-Page.jpg
I'm not sure whether it's completely right.

All other tweaks pass QA though.

**Comment by rayt86** [comment]
I created another issue where I'm going to make final adjustments to the navbar and CMS page including this "underline" fix. #526

**Comment by dpoirier** [comment]
Closing; work continued in #526.
